<link rel="stylesheet" type="text/css" href="<%=PATH%>/easyui/easyuiV153/themes/default/easyui.css">
<link rel="stylesheet" type="text/css" href="<%=PATH%>/easyui/easyuiV153/themes/icon.css">
<script type="text/javascript" src="<%=PATH%>/easyui/easyuiV153/jquery.min.js"></script>
<script type="text/javascript" src="<%=PATH%>/easyui/easyuiV153/jquery.easyui.min.js"></script>
<script type="text/javascript" src="<%=PATH%>/easyui/easyuiV153/locale/easyui-lang-zh_CN.js"></script>
<meta http-equiv="pragma" content="no-cache">
<meta http-equiv="cache-control" content="no-store">
<meta http-equiv="expires" content="0">
<meta http-equiv="keywords" content="keyword1,keyword2,keyword3">
<meta http-equiv="description" content="This is my page">

